In [92]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.max_rows', 500)

In [93]:
# read data
birth = pd.read_csv('birth.csv')
edu = pd.read_csv('edu.csv')
spouse_edu = pd.read_csv('spouse_edu.csv')
marstat = pd.read_csv('marstat.csv')

In [94]:
birth.columns = ['id', 'birth_year', 'gender']
edu = edu.rename(columns={'R0000100':'id', 'T9900000': 'grade'})
birth = pd.merge(birth, edu[['id', 'grade']], on='id', how='left')

In [95]:
# Create a range of age values from 21 to 60
age_values = np.arange(21, 61)

# Repeat the rows for each age value
num_repeats = len(age_values)
sample = birth.loc[birth.index.repeat(num_repeats)].reset_index(drop=True)

# Assign the age values to the repeated DataFrame
sample['age'] = np.tile(age_values, len(birth))

In [96]:
marstat.columns = ['id'] + list(range(1979,1995)) + list(range(1996,2019,2))
# deal with negative values
marstat = marstat.replace(-4, 0)
marstat[marstat<0] = np.nan

In [97]:
# convert categorical information to dummies
# if marital status is 0 (never married), 3 (divorced), or 6 (widowed), set the dummy to 0
columns_to_replace = marstat.columns[1:]  # Exclude the first column
marstat[columns_to_replace] = np.where((marstat[columns_to_replace] == 0) |
                                       (marstat[columns_to_replace] == 3) |
                                       (marstat[columns_to_replace] == 6), 0,
                                       marstat[columns_to_replace])
marstat[columns_to_replace] = np.where((marstat[columns_to_replace] == 1) |
                                       (marstat[columns_to_replace] == 2) |
                                       (marstat[columns_to_replace] == 5), 1,
                                       marstat[columns_to_replace])

In [98]:
new_cols = list(range(1995,2018,2))
for col in new_cols:
    marstat[col] = np.nan  # Assign nan (or any other initial value) to create an empty column

In [99]:
new_column_order = ['id'] + list(range(1979,2019))
marstat = marstat[new_column_order]

In [100]:
col_interpolate = marstat.columns[1:]
marstat[col_interpolate] = marstat[col_interpolate].interpolate(method='ffill', axis=1)
marstat[col_interpolate] = marstat[col_interpolate].interpolate(method='bfill', axis=1)

In [101]:
# convert a wide dataframe to a long one
marstat_melted = pd.melt(marstat, id_vars=['id'], var_name='year', value_name='marstat')

In [102]:
spouse_edu.columns = ['id'] + list(range(1979,1995)) + list(range(1996,2019,2))
for col in new_cols:
    spouse_edu[col] = np.nan  # Assign nan (or any other initial value) to create an empty column

In [103]:
spouse_edu = spouse_edu[new_column_order]

In [104]:
# deal with negative values
spouse_edu[spouse_edu<0] = np.nan

In [105]:
col_interpolate = spouse_edu.columns[1:]
spouse_edu[col_interpolate] = spouse_edu[col_interpolate].interpolate(method='ffill', axis=1)
spouse_edu[col_interpolate] = spouse_edu[col_interpolate].interpolate(method='bfill', axis=1)

In [106]:
spouse_edu_melted = pd.melt(spouse_edu, id_vars=['id'], var_name='year', value_name='spouse_grade')

In [107]:
# add birth year to calculate age
spouse_edu_melted = pd.merge(spouse_edu_melted, birth[['id', 'birth_year']], on='id', how='left')
spouse_edu_melted['year'] = spouse_edu_melted['year'].astype(int)
spouse_edu_melted['age'] = spouse_edu_melted['year'] - 1900 - spouse_edu_melted['birth_year']

In [108]:
# add spouse grade to the sample
sample = pd.merge(sample, spouse_edu_melted[['id', 'age', 'spouse_grade']],
                  on=['id', 'age'], how='left')

In [109]:
# add birth year to calculate age
marstat_melted = pd.merge(marstat_melted, birth[['id', 'birth_year']], on='id', how='left')
marstat_melted['year'] = marstat_melted['year'].astype(int)
marstat_melted['age'] = marstat_melted['year'] - 1900 - spouse_edu_melted['birth_year']

In [110]:
# add marital status to the sample
sample = pd.merge(sample, marstat_melted[['id', 'age', 'marstat']],
                  on=['id', 'age'], how='left')

In [111]:
sample['marstat'] = sample.groupby('id')['marstat'].transform(lambda x: x.bfill())
sample['spouse_grade'] = sample.groupby('id')['spouse_grade'].transform(lambda x: x.bfill())

In [112]:
sample['spouse_grade'] = np.where(sample['marstat']==0, np.nan, sample['spouse_grade'])

In [113]:
df = sample[(sample['marstat'] == 1) & (sample['spouse_grade'].isna())]

In [114]:
# Merge df1 and df2 with indicator=True
merged = sample.merge(df['id'], on='id', how='left', indicator=True)

# Filter rows where '_merge' is 'left_only' (meaning they exist in df1 but not in df2)
sample = merged[merged['_merge'] == 'left_only'].drop(columns='_merge')

In [115]:
df = sample[(sample['age'] == 21) & (sample['marstat'] == 1)]

In [116]:
# Merge df1 and df2 with indicator=True
merged = sample.merge(df['id'], on='id', how='left', indicator=True)

# Filter rows where '_merge' is 'left_only' (meaning they exist in df1 but not in df2)
sample = merged[merged['_merge'] == 'left_only'].drop(columns='_merge')

In [117]:
sample['mardur'] = 0

In [118]:
sample = sample[sample['grade'] >= 0]

In [119]:
sample.describe()

                  id     birth_year         gender          grade            age   spouse_grade        marstat    mardur
count  381920.000000  381920.000000  381920.000000  381920.000000  381920.000000  177469.000000  357524.000000  381920.0
mean     6232.138877      60.437683       1.444491      13.422392      40.500000      13.552389       0.496383       0.0
std      3649.654275       2.235038       0.496910       2.591834      11.543411       3.314985       0.499988       0.0
min         1.000000      57.000000       1.000000       0.000000      21.000000       0.000000       0.000000       0.0
25%      3093.750000      58.000000       1.000000      12.000000      30.750000      12.000000       0.000000       0.0
50%      6241.500000      60.000000       1.000000      12.000000      40.500000      13.000000       0.000000       0.0
75%      9339.250000      62.000000       2.000000      15.000000      50.250000      16.000000       1.000000       0.0
max     12685.000000      64.000000       2.000000      20.000000      60.000000      99.000000       1.000000       0.0

In [120]:
# Create a new column 'edu' based on 'grade'
def assign_edu(grade):
    if grade < 12:
        return 0
    elif grade == 12:
        return 1
    elif grade < 16:
        return 2
    elif grade == 16:
        return 3
    else:
        return 4

sample['edu'] = sample['grade'].apply(assign_edu)

In [121]:
female = sample[sample['gender'] == 2]
male = sample[sample['gender'] == 1]

In [122]:
# Group by 'age' and count the occurrences of 'marstat' values
equilibrium_f = female.groupby(['age', 'edu'])['marstat'].value_counts().unstack(fill_value=0)

# Rename the columns for clarity
equilibrium_f.columns = ['single_f', 'married_f']
equilibrium_f = equilibrium_f.reset_index()

In [129]:
# Group by 'age' and count the occurrences of 'marstat' values
equilibrium_m = male.groupby(['age', 'edu'])['marstat'].value_counts().unstack(fill_value=0)

# Rename the columns for clarity
equilibrium_m.columns = ['single_m', 'married_m']
equilibrium_m = equilibrium_m.reset_index()

In [133]:
equilibrium = pd.merge(equilibrium_f, equilibrium_m, on=['age', 'edu'], how='left')

In [134]:
equilibrium

     age  edu  single_f  married_f  single_m  married_m
0     21    0       322          0       649          0
1     21    1      1547          0      2390          0
2     21    2      1124          0      1138          0
3     21    3       675          0       616          0
4     21    4       576          0       511          0
5     22    0       296         26       590         59
6     22    1      1344        203      2198        192
7     22    2       993        131      1069         69
8     22    3       638         37       593         23
9     22    4       548         28       495         16
10    23    0       265         57       534        115
11    23    1      1183        364      2003        387
12    23    2       871        253       965        173
13    23    3       573        102       556         60
14    23    4       500         76       459         52
15    24    0       246         76       491        158
16    24    1      1030        517      1795        595
17    24    2       772        352       867        271
18    24    3       504        171       499        117
19    24    4       438        138       421         90
20    25    0       235         87       457        192
21    25    1       928        619      1622        768
22    25    2       701        423       786        352
23    25    3       431        244       447        169
24    25    4       396        180       386        125
25    26    0       233         89       438        211
26    26    1       838        709      1480        910
27    26    2       633        491       701        437
28    26    3       392        283       395        221
29    26    4       340        236       349        162
30    27    0       218        104       425        224
31    27    1       786        761      1403        987
32    27    2       601        523       659        479
33    27    3       346        329       352        264
34    27    4       321        255       315        196
35    28    0       213        109       408        241
36    28    1       752        795      1345       1045
37    28    2       564        560       618        520
38    28    3       314        361       310        306
39    28    4       299        277       285        226
40    29    0       206        116       397        252
41    29    1       741        806      1298       1092
42    29    2       539        585       596        542
43    29    3       286        389       296        320
44    29    4       266        310       238        273
45    30    0       195        127       393        256
46    30    1       722        825      1272       1118
47    30    2       521        603       573        565
48    30    3       261        414       265        351
49    30    4       241        335       207        304
50    31    0       193        129       385        264
51    31    1       699        848      1233       1157
52    31    2       521        603       563        575
53    31    3       240        435       244        372
54    31    4       226        350       200        311
55    32    0       191        131       379        270
56    32    1       692        855      1211       1179
57    32    2       512        612       553        585
58    32    3       229        446       231        385
59    32    4       205        371       183        328
60    33    0       192        130       376        273
61    33    1       678        869      1195       1195
62    33    2       505        619       543        595
63    33    3       226        449       220        396
64    33    4       202        374       161        350
65    34    0       190        132       373        276
66    34    1       666        881      1185       1205
67    34    2       494        630       534        604
68    34    3       223        452       215        401
69    34    4       196        380       153        358
70    35    0       187        135       375        274
71    35    1       667        880      1171       1219
72    35    2       484        640       523        615
73    35    3       217        458       204        412
74    35    4       191        385       146        365
75    36    0       186        136       373        276
76    36    1       661        886      1153       1237
77    36    2       482        642       519        619
78    36    3       212        463       200        416
79    36    4       185        391       138        373
80    37    0       183        139       370        279
81    37    1       653        894      1149       1241
82    37    2       485        639       519        619
83    37    3       207        468       194        422
84    37    4       181        395       129        382
85    38    0       182        140       371        278
86    38    1       656        891      1145       1245
87    38    2       485        639       505        633
88    38    3       205        470       192        424
89    38    4       185        391       126        385
90    39    0       186        136       369        280
91    39    1       662        885      1142       1248
92    39    2       478        646       492        646
93    39    3       210        465       191        425
94    39    4       184        392       129        382
95    40    0       189        133       372        277
96    40    1       662        885      1138       1252
97    40    2       480        644       491        647
98    40    3       207        468       189        427
99    40    4       185        391       131        380
100   41    0       190        132       371        278
101   41    1       664        883      1139       1251
102   41    2       490        634       497        641
103   41    3       205        470       186        430
104   41    4       185        391       130        381
105   42    0       185        137       370        279
106   42    1       665        882      1134       1256
107   42    2       489        635       494        644
108   42    3       203        472       185        431
109   42    4       186        390       129        382
110   43    0       183        139       371        278
111   43    1       666        881      1143       1247
112   43    2       489        635       495        643
113   43    3       201        474       180        436
114   43    4       188        388       130        381
115   44    0       186        136       369        280
116   44    1       665        882      1153       1237
117   44    2       474        650       491        647
118   44    3       203        472       182        434
119   44    4       185        391       122        389
120   45    0       188        134       373        276
121   45    1       672        875      1157       1233
122   45    2       480        644       492        646
123   45    3       205        470       188        428
124   45    4       188        388       120        391
125   46    0       184        138       371        278
126   46    1       669        878      1159       1231
127   46    2       494        630       499        639
128   46    3       213        462       185        431
129   46    4       190        386       124        387
130   47    0       188        134       374        275
131   47    1       675        872      1164       1226
132   47    2       493        631       499        639
133   47    3       220        455       185        431
134   47    4       192        384       125        386
135   48    0       190        132       374        275
136   48    1       680        867      1169       1221
137   48    2       499        625       502        636
138   48    3       226        449       185        431
139   48    4       195        381       125        386
140   49    0       190        132       374        275
141   49    1       684        863      1168       1222
142   49    2       510        614       509        629
143   49    3       227        448       189        427
144   49    4       202        374       125        386
145   50    0       191        131       377        272
146   50    1       688        859      1180       1210
147   50    2       517        607       514        624
148   50    3       225        450       189        427
149   50    4       208        368       128        383
150   51    0       192        130       378        271
151   51    1       695        852      1180       1210
152   51    2       521        603       510        628
153   51    3       227        448       191        425
154   51    4       204        372       121        390
155   52    0       195        127       377        272
156   52    1       709        838      1177       1213
157   52    2       527        597       511        627
158   52    3       227        448       190        426
159   52    4       207        369       121        390
160   53    0       196        126       378        271
161   53    1       717        830      1185       1205
162   53    2       529        595       508        630
163   53    3       225        450       196        420
164   53    4       209        367       118        393
165   54    0       198        124       381        268
166   54    1       720        827      1198       1192
167   54    2       531        593       516        622
168   54    3       223        452       196        420
169   54    4       208        368       114        397
170   55    0       173        110       334        245
171   55    1       651        736      1072       1061
172   55    2       490        537       468        553
173   55    3       193        402       176        372
174   55    4       193        329       105        358
175   56    0       141         90       269        211
176   56    1       554        642       894        925
177   56    2       411        458       421        480
178   56    3       160        367       149        326
179   56    4       168        277        95        291
180   57    0       113         74       207        176
181   57    1       451        524       763        766
182   57    2       345        391       345        398
183   57    3       144        304       127        259
184   57    4       145        219        82        243
185   58    0        91         59       153        139
186   58    1       354        433       623        629
187   58    2       280        320       279        328
188   58    3       114        243       103        207
189   58    4       111        167        65        198
190   59    0        63         37       109         89
191   59    1       245        326       448        448
192   59    2       214        250       220        255
193   59    3        93        179        77        159
194   59    4        91        129        54        150
195   60    0        37         22        61         57
196   60    1       154        207       275        299
197   60    2       142        153       140        175
198   60    3        61        126        53        122
199   60    4        72         83        30        128

In [135]:
sample.to_csv('sample79.csv',index=False)
equilibrium.to_csv('equilibrium.csv',index=False)